// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtmdcfkygqcqpajwhbdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bWRjZmt5Z3FjcXBhandoYmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzQ2NjQsImV4cCI6MjA3MTgxMDY2NH0.lV1AhIdfE8hKu0D8Eq9wV8zrqgVO-GX_A4H-1K4vOyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});